# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-18 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('edad_aproximada', models.IntegerField()),
                ('fecha_resgate', models.DateField()),
            ],
        ),
    ]
